config/routes.rb
Rails.application.routes.draw do
  get 'checkout/index'
  get 'checkout/place_order'
  get 'checkout/thank_you'
  devise_for :users
  root 'home#index'
  
  get 'catalog/index'
  get 'catalog/show/:id', to: 'catalog#show'
  get 'catalog/search', to: 'catalog#search'
  get 'catalog/latest'
  get 'catalog/rss', to: 'catalog#rss', format: 'xml'
  
  get 'cart/clear', to: 'cart#clear'
  get 'cart/:id', to: 'cart#add'
  post 'cart/:id', to: 'cart#add'
  get 'cart/dell/:id', to: 'cart#dell'
  
  get 'checkout', to: 'checkout#index'
  post 'checkout', to: 'checkout#place_order'
  get 'checkout/place_order', to: 'checkout#place_order'
  get 'checkout/thanks', to: 'checkout#thank_you'
  get 'checkout/payment', to: 'checkout#payment'
  get '/checkout/secret', to: 'checkout#secret' 
  
  #get '/checkout/confirm', to: 'checkout#confirm' 
  #post '/checkout/confirm', to: 'checkout#confirm' 
  
  resources :books
  resources :publishers
  get 'about', to: 'about#index'
  #get 'about/show', to: 'about#show'
  #get 'about/add', to: 'about#add'
  resources :author
  resources :posts do
    resources :comments
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart < ApplicationRecord
    has_many :cart_items
    has_many :books, through: :cart_items

    def total
        cart_items.inject(0) {|sum, n| n.price * n.amount + sum}
    end

    def add(book_id)
       #items = cart_items.find_all_by_book_id(book_id)
       items = cart_items.all.where(" book_id = ?", book_id)
        book = Book.find(book_id)
        if items.size < 1
            ci = cart_items.create(book_id: book_id, amount: 1, price: book.price)
        else
            ci = items.first
            ci.update_attribute(:amount, ci.amount + 1)
        end
        ci
    end
    def dell(book_id)
        items = cart_items.all.where(" book_id = ?", book_id)
         #if items.first.amount != 0
         if items.first.amount > 0
            ci = items.first
            ci.update_attribute(:amount, ci.amount - 1)
         else
            items.first.id.destroy
         end
         ci
    end
end

#Note that we use the new has_many :through syntax
#With the syntax, we can access books belonging to a cart directly by using
#@cart_object.books, even though the two classes don’t have a direct relationship. Without
#using the new :through option, we would need to laboriously go through the CartItem class:
#@cart_object.cart_items.map {|ci| ci.book }.

#inject is a method for arrays and other enumerable objects that can be used to calculate
#sums, factorials, and so on of all the items in the container object. It takes one initial parameter
#(in our case, 0) and passes it as the first block parameter (in our case, sum) for the first iteration.
#Then it passes each item of cart_items to the block as n, one at a time, updating the sum all the
#time. After it has gone through all of the items, it returns the final value of sum.

app/controllers/cart_controller.rb
class CartController < ApplicationController
    before_action :initialize_cart

    def add
        #byebug
        @book = Book.find(params[:id])
        if request.xhr?
            @item = @cart.add(params[:id])
            flash.now[:cart_notice] = "Added #{@item.book.title}"
            respond_to do |format|
                format.js { render partial: 'cart/add_with_ajax' }
            end
        elsif
            request.post?
            @item = @cart.add(params[:id])
            flash[:cart_notice] = "Added #{@item.book.title}"
            redirect_to catalog_index_path
        else
            render
        end
    end
    def dell
        #byebug
        @book = Book.find(params[:id])
        if request.xhr?
            @item = @cart.dell(params[:id])
            flash.now[:cart_notice] = "Dell #{@item.book.title}"
            respond_to do |format|
                format.js { render partial: 'cart/add_with_ajax' }
            end
        elsif request.post?
            @item = @cart.dell(params[:id])
            flash[:cart_notice] = "Dell #{@item.book.title}"
            redirect_to session[:return_to] || {:controller => "catalog"}
        else
            render
        end
    end
    def clear
        #byebug
        if request.xhr?
            @cart.cart_items.destroy_all
            flash.now[:cart_notice] = "Cleared the cart"
            respond_to do |format|
                format.js { render partial: 'cart/add_with_ajax' }
            end
        elsif request.post?
            @cart.cart_items.destroy_all
            flash[:cart_notice] = "Cleared the cart"
            redirect_to session[:return_to] || {:controller => "catalog"}
        else
            render
        end
    end
end
=begin
        if request.xhr?
            @item = @cart.add(params[:id])
            flash.now[:cart_notice] = "Added #{@item.book.title}"
            #render :action => "add_with_ajax"
            render "cart/add_with_ajax"
        elsif request.post?
            @item = @cart.add(params[:id])
            flash[:cart_notice] = "Added #{@item.book.title}"
            redirect_to session[:return_to] || {:controller => "catalog"}
        else
            render
        end

=end
    #if request.post?
    #@item = @cart.add(params[:id])
    #flash[:cart_notice] = "Added #{@item.book.title}"
    #flash[:prueba] = "TESTING FLASH"
    #redirect_to catalog_index_path


#The filter makes the controller call the initialize_cart method before running an action. We
#could implement the initialize_cart method in both CartController and CatalogController, but
#since we don’t want to repeat ourselves, we put the definition to the ApplicationController (in
#app/controllers/application.rb), which is by default the parent class of all our controllers.

app/helpers/cart_helper.rb
module CartHelper
end

app/views/cart/_add_with_ajax.html.erb
<% if flash[:cart_notice] %>
    <%= render "cart/cart_notice" %>
<% end %>

<div id="shopping_cart">
    <h3>Your Shopping Cart-AJAXS</h3>
    <% @cart.cart_items.each do |item|%>
        <li id="cart_item_<%= item.book.title %>">
            <%= render partial: "cart/item", locals: {item: item} %>
        </li>        
    <% end %>
    </ul>

<p id="cart_total"><strong>Total: $<%= sprintf("%0.2f", @cart.total) %> </strong></p>

<% unless @cart.cart_items.empty? %>
        <p id="clear_cart_link">
        <small><%= link_to "Clear Cart", cart_clear_path, remote: true %></small>
        </p>
<% end %>
<% unless @cart.cart_items.empty? %>
    <p><strong>
            <%= link_to "Proceed to Checkout", checkout_path unless controller.controller_name == 'checkout' %>
    </strong></p>
    </div>
<% end %>

app/views/cart/_add_with_ajax.js.erb
document.querySelector('#results').innerHTML = '<%= escape_javascript(render 'cart/add_with_ajax.html')%>'

app/views/cart/_cart.html.erb
<% if flash[:cart_notice] %>
    <%= render "cart/cart_notice" %>
<% end %>

<h3>Your Shopping Cart</h3>
<ul>
   <% @cart.cart_items.each do |item|%>
    <li id="cart_item_<%= item.book.title %>">
        <%= render partial: "cart/item", locals: {item: item} %>
    </li>
    
   <% end %>
</ul>
<p id="cart_total"><strong>Total: $<%= sprintf("%0.2f", @cart.total) %> </strong></p>

<% unless @cart.cart_items.empty? %>
        <p id="clear_cart_link">
        <small><%= link_to "Clear Cart", cart_clear_path, remote: true %></small>
        </p>
<% end %>
<% unless @cart.cart_items.empty? %>
    <p><strong>
            <%= link_to "Proceed to Checkout", checkout_path unless controller.controller_name == 'checkout' %>
    </strong></p>
    </div>
<% end %>

app/views/cart/_cart.js.erb
document.querySelector('#results').innerHTML = '<%= escape_javascript(render 'cart/cart.html')%>'

app/views/cart/_cart_notice.html.erb
<p id="cart_notice"><%= flash[:cart_notice] %></p>
<br>
<p><%= flash[:prueba] %></p>

app/views/cart/_item.html.erb
<% if (item.price * item.amount) != 0 %>
    <%= link_to item.book.title, book_path(item.book.id) %>
    <%= pluralize(item.amount, "pc", "pcs") %>, $<%= sprintf("%0.2f", item.price * item.amount) %>
    <%= link_to "+", "/cart/#{item.book.id}", remote: true %>|
    <%= link_to "-", "/cart/dell/#{item.book.id}", remote: true %>
<% end %>

app/views/cart/add.html.erb
<strong>Please confirm adding <em>"<%= @book.title %>"</em> to your shopping cart.</strong>
<%= button_to "Confirm", "/cart/#{params[:id]}", remote: true %> <br>
<%= button_to "Go back", catalog_index_path, method: :get %>