config/routes.rb
Rails.application.routes.draw do
  get 'checkout/index'
  get 'checkout/place_order'
  get 'checkout/thank_you'
  devise_for :users
  root 'home#index'
  
  get 'catalog/index'
  get 'catalog/show/:id', to: 'catalog#show'
  get 'catalog/search', to: 'catalog#search'
  get 'catalog/latest'
  get 'catalog/rss', to: 'catalog#rss', format: 'xml'
  
  get 'cart/clear', to: 'cart#clear'
  get 'cart/:id', to: 'cart#add'
  post 'cart/:id', to: 'cart#add'
  get 'cart/dell/:id', to: 'cart#dell'
  
  get 'checkout', to: 'checkout#index'
  post 'checkout', to: 'checkout#place_order'
  get 'checkout/place_order', to: 'checkout#place_order'
  get 'checkout/thanks', to: 'checkout#thank_you'
  get 'checkout/payment', to: 'checkout#payment'
  get '/checkout/secret', to: 'checkout#secret' 
  
  #get '/checkout/confirm', to: 'checkout#confirm' 
  #post '/checkout/confirm', to: 'checkout#confirm' 
  
  resources :books
  resources :publishers
  get 'about', to: 'about#index'
  #get 'about/show', to: 'about#show'
  #get 'about/add', to: 'about#add'
  resources :author
  resources :posts do
    resources :comments
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/author.rb
class Author < ApplicationRecord
    has_and_belongs_to_many :books
    
    validates :first_name, :last_name, presence: true

    def name
        "#{first_name} #{last_name}"
    end
end

app/controllers/author_controller.rb
class AuthorController < ApplicationController
  def index
    @authors = Author.all
    @page_title = 'Listing authors'
  end

  def show
    @author = Author.find(params[:id])
    session[:current_user_id] = @author.name
    @page_title = @author.name
  end

  
  def new
    @author = Author.new
    @page_title = 'Create new author'
  end
  def create
    #byebug
    @author = Author.new(params[:author].permit(:first_name, :last_name))
    if @author.save
      flash[:notice] = "Author #{@author.name} was successfully created."
      redirect_to @author
    else
      @page_title = "Create new author"
      flash[:alert] = "Author NOT successfully created."
      render 'new'
    end
  end

  def edit
    @author = Author.find(params[:id])
    @page_title = 'Edit author'
  end

  def update
    #byebug
    @author = Author.find(params[:id])
    if @author.update(params[:author].permit(:first_name, :last_name))
      flash[:notice] = "Author: #{@author.name} was successfully updated."
      redirect_to @author
    else
      @page_title = 'Edit author'
      render 'edit'
    end
  end

  def destroy
    @author = Author.find(params[:id])
    flash[:notice] = "Successfully deleted author: #{@author.name}"
    @author.destroy
    redirect_to  author_index_path
  end

  
end

app/helpers/admin/author_helper.rb
module Admin::AuthorHelper
end

app/views/author/_author.html.erb
<tr>
    <!--<td><%= link_to author.name, :action => 'show', :id => author %></td>-->
    <td><%= link_to author.name, author_path(author) %></td>
    <!--<td><%= link_to 'Edit', :action => 'edit', :id => author %></td>-->
    <% if current_user.email == "chino@gmail.com"%>
        <td><%= link_to 'Edit', edit_author_path(author) %></td>
        <!--<%= button_to 'Delete', {:action => 'destroy', :id => author},:confirm =>"Are you sure you want to delete author #{author.name}?" %>-->
        <td><%= button_to 'Delete', author_path(author), method: :delete, data: {confirm: "Are you sure?"} %></td>
    <% end %>
</tr>

app/views/author/_form.html.erb
<p><label for="author_first_name">First name</label><br/>
<%= text_field 'author', 'first_name' %></p>
<p><label for="author_last_name">Last name</label><br/>
<%= text_field 'author', 'last_name' %></p>

app/views/author/edit.html.erb
<%=@author.errors.full_messages if @author.errors.any?%>

<%= form_with model: @author do |form| %>
  <%= render 'form' %>
  <%= form.submit "Update" %>
<% end %>

<%= link_to 'Show', author_path(@author) %>
<%= link_to 'Back', author_index_path %>

app/views/author/index.html.erb
<table>
    <tr>
        <th>Name</th>
        <% if current_user.email == "chino@gmail.com"%>
            <th>Edit</th>
            <th>Delete</th>
        <% end %>
    </tr>
    <%= render :partial => 'author', :collection => @authors %>
</table>

<!--<p><%= link_to 'Add a new author', :action => 'new' %></p>>-->
<p><%= link_to 'Add a new author',  new_author_path %></p>

app/views/author/new.html.erb
<%=@author.errors.full_messages if @author.errors.any?%>

<%= form_with url: author_index_path , method: :post do |form| %>
  <%= render 'form' %>
  <%= form.submit "Create" %>
<% end %>

<%= link_to 'Back', :action => 'index' %>

app/views/author/show.html.erb
<dl>
    <dt>First Name</dt>
    <dd><%= @author.first_name %></dd>
    <dt>Last Name</dt>
    <dd><%= @author.last_name %></dd>
</dl>

<%= session[:current_user_id] %>
<!--<p><%= link_to 'Edit', :action => 'edit', :id => @author %> |-->
<p><td><%= link_to 'Edit', edit_author_path(@author) %></td> |
<!--<%= link_to 'Back', :action => 'index' %></p>-->
<%= link_to 'Back', author_index_path %></p>